import type { EditorThemeClasses } from 'lexical';

export const MARKDOWN_COMPOSER_THEME: EditorThemeClasses = {
  paragraph: 'text-sm leading-relaxed text-[var(--agyn-dark)]',
  quote: 'border-l-4 border-[var(--agyn-blue)] bg-[var(--agyn-bg-light)] pl-3 pr-2 py-2 text-sm leading-relaxed text-[var(--agyn-dark)] italic rounded-[6px]',
  list: {
    nested: {
      listitem: 'text-sm leading-relaxed text-[var(--agyn-dark)]',
    },
    ol: 'ml-4 list-decimal space-y-1 text-sm leading-relaxed text-[var(--agyn-dark)]',
    ul: 'ml-4 list-disc space-y-1 text-sm leading-relaxed text-[var(--agyn-dark)]',
  },
  listitem: 'text-sm leading-relaxed text-[var(--agyn-dark)]',
  heading: {
    h1: 'text-2xl font-semibold text-[var(--agyn-dark)]',
    h2: 'text-xl font-semibold text-[var(--agyn-dark)]',
    h3: 'text-lg font-semibold text-[var(--agyn-dark)]',
    h4: 'text-base font-semibold text-[var(--agyn-dark)]',
    h5: 'text-sm font-semibold text-[var(--agyn-dark)]',
    h6: 'text-sm font-semibold text-[var(--agyn-dark)] uppercase tracking-wide',
  },
  text: {
    bold: 'font-semibold',
    italic: 'italic',
    underline: 'underline decoration-[var(--agyn-purple)] decoration-2 underline-offset-2',
    code: 'rounded bg-[var(--agyn-bg-light)] px-1.5 py-0.5 font-mono text-[var(--agyn-purple)] text-sm',
  },
  link: 'text-[var(--agyn-blue)] underline underline-offset-2 transition-colors hover:text-[var(--agyn-purple)]',
  code: 'block rounded-[10px] bg-[var(--agyn-bg-light)] p-3 font-mono text-sm leading-relaxed text-[var(--agyn-dark)] overflow-x-auto',
  codeHighlight: {
    atrule: 'text-[#c678dd]',
    attrName: 'text-[#d19a66]',
    attribute: 'text-[#98c379]',
    boolean: 'text-[#56b6c2]',
    builtin: 'text-[#56b6c2]',
    cdata: 'text-[#5c6370]',
    char: 'text-[#98c379]',
    className: 'text-[#e5c07b]',
    comment: 'text-[#5c6370]',
    constant: 'text-[#d19a66]',
    deleted: 'text-[#e06c75]',
    doctype: 'text-[#7f848e]',
    entity: 'text-[#56b6c2]',
    function: 'text-[#61afef]',
    important: 'text-[#c678dd]',
    inserted: 'text-[#98c379]',
    keyword: 'text-[#c678dd]',
    number: 'text-[#d19a66]',
    operator: 'text-[#56b6c2]',
    property: 'text-[#61afef]',
    punctuation: 'text-[#abb2bf]',
    regex: 'text-[#98c379]',
    selector: 'text-[#e06c75]',
    string: 'text-[#98c379]',
    symbol: 'text-[#56b6c2]',
    tag: 'text-[#e06c75]',
    url: 'text-[#56b6c2]',
    variable: 'text-[#e06c75]',
  },
};
